# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Travelers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Travelers

  target 'TravelersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TravelersUITests' do
    # Pods for testing
  end
  
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'GoogleSignIn', '~> 5.0'

  pod 'FBSDKCoreKit', '~> 6.0.0'
  pod 'FBSDKLoginKit', '~> 6.0.0'
  pod 'FBSDKShareKit', '~> 6.0.0'

end
